create table happydog_comments (
  id integer primary key generated by default as identity,
  comment text not null,
  date_created TIMESTAMP NOT NULL default now(),
  date_modified TIMESTAMP,
  note_id INTEGER REFERENCES happydog_notes(id) ON DELETE CASCADE
);