create table happydog_checklist (
  id integer primary key generated by default as identity,
  user_id text not null,
  value BOOLEAN default false,
  date_created TIMESTAMP NOT NULL default now(),
  date_modified TIMESTAMP
);